"""campos del censo

Revision ID: 538ce093b0cb
Revises: 27af2fbbf3b9
Create Date: 2026-09-30 17:32:30.295432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538ce093b0cb'
down_revision: Union[str, Sequence[str], None] = '27af2fbbf3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('census_number', sa.Integer(), nullable=True))
    op.add_column('plants', sa.Column('dap', sa.Float(), nullable=True))
    op.add_column('plants', sa.Column('trunk_shape', sa.String(length=80), nullable=True))
    op.create_unique_constraint('uq_plants_census_number', 'plants', ['census_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plants_census_number', 'plants', type_='unique')
    op.drop_column('plants', 'trunk_shape')
    op.drop_column('plants', 'dap')
    op.drop_column('plants', 'census_number')
    # ### end Alembic commands ###
