"""modelo plant

Revision ID: a5111ffa4082
Revises: 8045eee03791
Create Date: 2026-09-30 17:01:49.947070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5111ffa4082'
down_revision: Union[str, Sequence[str], None] = '8045eee03791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comun', sa.String(length=120), nullable=False),
    sa.Column('especie_cientifica', sa.String(length=160), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plants_qr_code_url'), 'plants', ['qr_code_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plants_qr_code_url'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
